#!/usr/bin/env ruby

if ARGV.size < 2
  puts 'awstats_render host outputdir'
  puts 'Renders all pages from awstats generated data.'
  exit 1
end

def run_command page = nil
  if page
    eq_page = '=' + page
    dot_page = '.' + page
  end
  command = [
    '/usr/lib/cgi-bin/awstats.pl',
    "-config=#{ARGV[0]}",
    '-staticlinks',
    "-output#{eq_page}", 
    "> #{File.join(ARGV[1], "awstats.#{ARGV[0]}#{dot_page}.html")}"
  ].join(' ')
  puts command
  system command
end

run_command

%w(
  alldomains
  allhosts
  lasthosts
  unknownip
  allemails
  lastemails
  allemailr
  lastemailr
  alllogins
  lastlogins
  allrobots
  lastrobots
  urldetail
  urlentry
  urlexit
  osdetail
  browserdetail
  unknownbrowser
  unknownos
  refererse
  refererpages
  keyphrases
  keywords
  errors404
).each do |page|
  run_command page
end
