#!/bin/bash

if [[ $1 = "--help" ]]; then
  echo dr - Dirty Repositories [version 0.1]
  exit
fi


echo Repositories in ~/workspace that are not clean:
for f in `ls ~/workspace`
do
  if [ -d ~/workspace/$f/.git ]; then
    branch=`cd ~/workspace/$f && git symbolic-ref -q HEAD 2>/dev/null | sed 's/refs\/heads\///'`
    uncommitted=`cd ~/workspace/$f && git st -s`
    not_pushed=`cd ~/workspace/$f && git diff --name-only origin/$branch`
    if [[ $uncomitted || $not_pushed ]]; then
      echo $f
    fi
  fi
done

