#!/bin/bash

# https://gist.github.com/2371406
# version 0.1 - Not much error handling yet.
# version 0.2 - Added --edit command
# version 0.3 - generate password and copy to clipboard
#               Don't re-encrypt file if not changed
#               Copy retrieved password to clipboard
#               Improve display of multiple passwords
# version 0.4 - Add support for Git Bash aka MinGW
#
# Add to ~/bin/pw and chmod +x it.
# See bottom of file for usage or run `pw` without args.

if [[ -f ~/.pwconfig ]]; then
  source ~/.pwconfig
fi

PASSWORD_GPG=$PASSWORD_DIR/$PASSWORD_FILE.gpg
PASSWORD_TEMP=$TEMP/$PASSWORD_FILE

if [[ -z $PASSWORD_DIR || -z $PASSWORD_FILE || -z $EDIT ]]; then
  echo 'A ~/.pwconfig file must exist with the following configuration:'
  echo 'PASSWORD_DIR=password/dir'
  echo 'PASSWORD_FILE=.password.csv (no gpg extension)'
  echo 'EDIT=path/to/editor'
  echo ''
  exit 1
fi

if [[ $# > 0 ]]; then
  echo 'Enter encryption password:'
  read -s secret
  OPTIONS=--no-permission-warning\ --no-secmem-warning\ --force-mdc\ --no-tty\ -q\ --no-use-agent\ --yes\ --passphrase=$secret\ --homedir\ ~/.gnupg
fi

function encrypt {
  gpg $OPTIONS -c -o $PASSWORD_GPG $PASSWORD_TEMP
  cleanup
  echo 'Password file updated.'
}

function decrypt {
  gpg $OPTIONS -o $PASSWORD_TEMP $PASSWORD_GPG
}

function backup_decrypted_file {
  cp $PASSWORD_TEMP $PASSWORD_TEMP.bak
}

function cleanup {
  rm -f $PASSWORD_TEMP $PASSWORD_TEMP.bak
}

function init_password_csv {
  encrypt
}

function edit_password_csv {
  decrypt
  backup_decrypted_file
  $EDIT $PASSWORD_TEMP
  if diff $PASSWORD_TEMP $PASSWORD_TEMP.bak > /dev/null; then
    cleanup
    echo 'No changes made.'
  else
    encrypt
  fi
}

function add_password {
  pass=`tr -dc A-Za-z0-9_ < /dev/urandom | head -c8`

  copy_password
  echo Password copied to clipboard.

  decrypt
  echo $1,$2,$pass >> $PASSWORD_FILE
  encrypt
}

function copy_password {
  if [[ $TERM == 'cygwin' ]]; then
    echo $pass > /dev/clipboard
  else
    echo $pass | xsel -i
  fi
}

function match_command {
  cat $PASSWORD_TEMP | sed -n "s/.*$1.*,\(.*\)/\1/p"
}

function matched_site {
  cat $PASSWORD_TEMP | sed -n "s/\(.*$1.*\),.*,.*/\1/p"
}

function matched_login {
  cat $PASSWORD_TEMP | sed -n "s/.*$1.*,\(.*\),.*/\1/p"
}

function find_password {
  decrypt
  matches=`match_command $1 | wc -l`
  if [ $matches -eq 0 ]; then
    echo No matches.
  elif [ $matches -eq 1 ]; then
    pass=`match_command $1 | tr -d '\n'`
    copy_password
    echo Password for $(matched_site $1) copied to clipboard. Login: $(matched_login $1)
  else
    echo Multiple passwords matched. Displaying:
    cat $PASSWORD_TEMP | grep $1
  fi
  rm -f $PASSWORD_TEMP
}

if [ $# == 2 ]; then
  add_password $1 $2
elif [ $# == 1 ]; then
  if [ $1 == '--init' ]; then
    init_password_csv
  elif [ $1 == '--edit' ]; then
    edit_password_csv
  else
    find_password $1
  fi
else
  echo 'Usage (1): pw --init          Encrypts a prepared .passwords.csv file'
  echo 'Usage (2): pw --edit          Edit the .passwords.csv file'
  echo 'Usage (3): pw TERM            find a password'
  echo 'Usage (4): pw URL/NAME LOGIN  add a password (generated and copied to clipboard)'
  echo 'Add or view a password from a GPG encrypted password file.'
  echo
  echo 'TERM          Enter a partial site name or URL'
  echo 'URL/NAME      A name or URL of a site'
  echo 'LOGIN         Email address or username used to login'
  echo
  exit
fi

