#!/bin/env bash

output="$1"
input="${output}.orig"

sudo mv "$output" "$input"
sudo ffmpeg -i "$input" -map_metadata -1 -c:v copy -c:a copy -nostats "$output"
if [[ -f "$output" && $? == 0  ]]; then
  sudo chown plex:plex "$output"
  sudo rm "$input"
else
  sudo mv "$input" "$output"
fi

